### ISSUE TITLE
Can I test your code in my video

### ISSUE THREAD

**Issue by caodoanh2001** [Lijun-Yu/zero_virus#1]
Hi team,

Can i run your code to test on my own video?

Thanks!

**Comment by Lijun-Yu** [comment]
Of course! But it will take a little effort to change the function [`get_jobs`](https://github.com/Lijun-Yu/zero_virus/blob/master/utils/run.py#L21). For now, it takes the AI City Challenge dataset as input. 

You can write your own `get_jobs` to return a list of [`VideoJob`](https://github.com/Lijun-Yu/zero_virus/blob/master/system/video.py#L20) for the system to process.

Apart from the code, you will also need to provide the [region](https://github.com/Lijun-Yu/zero_virus/tree/master/monitor/regions) and [tracks](https://github.com/Lijun-Yu/zero_virus/tree/master/monitor/tracks) based on the camera view of your video.

**Comment by caodoanh2001** [comment]
Thanks for your response, I will try it!

**Comment by caodoanh2001** [comment]
Hi Yu,

Can I test video to count other classes on my video? For example it's maybe Bicycle, Motorbike instead of only car and truck?

**Comment by dmitmatveev** [comment]
Hi, @caodoanh2001 !
Did you adapt ```get_jobs()``` function for working with your own single video?
Could you share it please?
