### ISSUE TITLE
Can I test my video with other classes

### ISSUE THREAD

**Issue by caodoanh2001** [Lijun-Yu/zero_virus#2]
Hi Yu,

Thanks for your great work,
I wonder if you use Detectron2 as a detector, it maybe count other classes (instead of car and truck),
In detail, i want to count class Motorbike, bicycle and Bus.
Can i do that?

**Comment by Lijun-Yu** [comment]
Yes, it can be easily extended to other classes in the COCO dataset. You'll need to do the following:

1. Create a new type at [ObjectType](https://github.com/Lijun-Yu/zero_virus/blob/master/detector/base.py#L11)
2. Define a mapping from COCO at [TYPE_MAPPING](https://github.com/Lijun-Yu/zero_virus/blob/master/detector/detectron2.py#L17).
3. Define non-maximum suppression mapping at [NMS_MAPPING](https://github.com/Lijun-Yu/zero_virus/blob/master/detector/detectron2.py#L21), typically `ObjectType.xxx: (ObjectType.xxx, 0)` would be fine. Types with the same NMS mapping will be treated as the same type during NMS.
4. Define track mapping at [TRACK_MAPPINGS](https://github.com/Lijun-Yu/zero_virus/blob/master/tracker/trmot.py#L11), typically `ObjectType.xxx: ObjectType.xxx` would be fine. Types with the same track mapping will be tracked in the same tracker.

**Comment by Lijun-Yu** [comment]
Note that currently `bus` is included in `ObjectType.Car`, you may want to change [TYPE_MAPPING](https://github.com/Lijun-Yu/zero_virus/blob/master/detector/detectron2.py#L17) if you want to treat them separately.

**Comment by caodoanh2001** [comment]
Thanks for your help, do your instruction now I can count other class. but what is `0` mean in `ObjectType.xxx: (ObjectType.xxx, 0)`

**Comment by caodoanh2001** [comment]
Thanks for your help, now i can count other classes
Best regards!
