### ISSUE TITLE
about annotation of movement

### ISSUE THREAD

**Issue by caodoanh2001** [Lijun-Yu/zero_virus#3]
Hi Yu

as you mentioned in [Evaluate](https://github.com/Lijun-Yu/zero_virus#evaluate), each video has a screenshot of movement and you annotate movements as json file from this.

I wonder how your code can run on private Test set B of AI City challenge, can you are allowed to annotate movement on Test set B?

**Comment by Lijun-Yu** [comment]
See [FAQ](https://www.aicitychallenge.org/2020-faqs/) track1 No. 5. Test set A and B share the same set of cameras.

**Comment by caodoanh2001** [comment]
Thanks you, your support mean a lot for me
