### ISSUE TITLE
how do you get the S1_Effectiveness score ？

### ISSUE THREAD

**Issue by Graceqi** [Lijun-Yu/zero_virus#7]
Is it true that only the online evaluation system will give S1_Effectiveness  scores？

**Comment by Lijun-Yu** [comment]
The correct S1_Effectiveness can only be given by the evaluation. The organizer did provide a script `efficiency_base.py` to measure the local machine at https://www.aicitychallenge.org/2020-data-and-evaluation/, but I'm not sure if it's still available.

**Comment by Graceqi** [comment]
thank you so much!


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Lijun-Yu/zero_virus"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月21日(星期二) 中午12:23
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Lijun-Yu/zero_virus] how do you get the S1_Effectiveness score ？ (Issue #7)





 
The correct S1_Effectiveness can only be given by the evaluation. The organizer did provide a script efficiency_base.py to measure the local machine at https://www.aicitychallenge.org/2020-data-and-evaluation/, but I'm not sure if it's still available.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
